## Level sourcing — reverse play from the solved position.
##
## NO DATASET IS DOWNLOADED, EVER, at build time or at runtime. Boxoban's 1.5 M
## levels are a ~1 GB text corpus in another repo, and a coworld that fetched it
## would be neither hermetic nor "held out" (a published corpus is exactly what
## a language model may have memorised). Instead every level is GENERATED BY
## REVERSE PLAY from the solved position — gym-sokoban's own generation method
## — which yields, as a free by-product, the EXACT optimal push count, the
## number the tiers are defined by.
##
## Every level is a pure function of `(seed, levelIndex, tier)`. Nothing the
## policy does can shift a draw, reorder draws, or consume one out from under a
## later level: level k's grid is identical no matter what happened in level
## k-1, which is what makes per-tier solve rates comparable across policies.

import std/[os, strutils, tables]
import sim_types, grid, deadlock

const
  FallbackLevelDir* = "data/levels"

type
  Level* = object
    state*: LevelState        ## the starting position
    tier*: Tier
    optPushes*: int
    dead*: DeadSquares
    tierRelaxed*: bool

proc mix64*(a, b, c, d: int64): uint64 =
  ## splitmix64 over the mixed words — a pure HASH, never a consumed stream.
  var x = uint64(a) * 0x9E3779B97F4A7C15'u64
  x = x xor (uint64(b) + 0xBF58476D1CE4E5B9'u64 + (x shl 6) + (x shr 2))
  x = x xor (uint64(c) + 0x94D049BB133111EB'u64 + (x shl 6) + (x shr 2))
  x = x xor (uint64(d) + 0xD6E8FEB86659FD93'u64 + (x shl 6) + (x shr 2))
  x = x xor (x shr 30)
  x = x * 0xBF58476D1CE4E5B9'u64
  x = x xor (x shr 27)
  x = x * 0x94D049BB133111EB'u64
  x = x xor (x shr 31)
  x

proc hashAt(seed: int64, levelIndex, attempt, salt: int): uint64 {.inline.} =
  mix64(seed, int64(levelIndex), int64(attempt), int64(salt))

proc drawRoom(seed: int64, levelIndex, attempt: int): Board =
  ## The border ring is wall, the 8 x 8 interior all floor, then
  ## `8 + (h(1) mod 5)` interior cells are drawn and set to wall. Repeats simply
  ## re-set the same cell, so the realised wall count may be lower —
  ## deterministic, no retry loop.
  for x in 0 ..< GridSize:
    result.wall[cellIndex(x, 0)] = true
    result.wall[cellIndex(x, GridSize - 1)] = true
  for y in 0 ..< GridSize:
    result.wall[cellIndex(0, y)] = true
    result.wall[cellIndex(GridSize - 1, y)] = true
  let count = 8 + int(hashAt(seed, levelIndex, attempt, 1) mod 5)
  for j in 0 ..< count:
    let
      x = 1 + int(hashAt(seed, levelIndex, attempt, 10 + j) mod 8)
      y = 1 + int(hashAt(seed, levelIndex, attempt, 100 + j) mod 8)
    result.wall[cellIndex(x, y)] = true

proc drawTargets(
  board: var Board, seed: int64, levelIndex, attempt: int
): bool =
  ## Four distinct floor cells by rejection sampling over the floor list.
  let cells = board.floorCells()
  if cells.len < BoxCount:
    return false
  var
    chosen: seq[int] = @[]
    salt = 200
  while chosen.len < BoxCount and salt < 400:
    let cell = cells[int(hashAt(seed, levelIndex, attempt, salt) mod
      uint64(cells.len))]
    inc salt
    if cell notin chosen:
      chosen.add(cell)
  if chosen.len < BoxCount:
    return false
  for cell in chosen:
    board.target[cell] = true
  true

type
  GoalNode = object
    boxes: array[BoxCount, int]
    player: int
    depth: int

proc encodeGoal(node: GoalNode): uint64 =
  result = uint64(node.player)
  for box in node.boxes:
    result = (result shl 8) or uint64(box)

proc stateOf(board: Board, node: GoalNode): LevelState =
  result.board = board
  result.boxes = node.boxes
  result.player = node.player

proc backwardBfs(
  board: Board, targets: seq[int], targetDepth, nodeCap: int
): tuple[reached: int, atTarget: seq[GoalNode], deepest: seq[GoalNode]] =
  ## Backward BFS over PULL space. The successor relation is the pull: for a box
  ## at `q` and a direction `d`, the pull is legal iff `q - d` and `q - 2d` are
  ## both free floor AND `q - d` is in the player's reachable region; it yields
  ## the box at `q - d` and the player at `q - 2d`. Because a pull is exactly a
  ## push run backwards, BFS depth in this graph IS the minimum number of pushes
  ## needed to solve the resulting position.
  ##
  ## Only two depths are ever retained: the requested `targetDepth` (the band
  ## draw) and the deepest completed depth (the relaxed fallback). Keeping every
  ## depth would hold 200 000 nodes of history for no reader.
  var
    seen = initTable[uint64, bool]()
    queue: seq[GoalNode] = @[]
    work: LevelState
    region: array[GridCells, bool]
    blocked: array[GridCells, bool]
    nextRegion: array[GridCells, bool]
  work.board = board
  var start: GoalNode
  for i in 0 ..< BoxCount:
    start.boxes[i] = targets[i]
  start.depth = 0
  # All distinct normalisations of "player anywhere on free floor" seeded at
  # depth 0.
  work.boxes = start.boxes
  for cell in 0 ..< GridCells:
    work.player = cell
    if not work.isFree(cell):
      continue
    var node = start
    node.player = work.normalisedPlayer()
    let key = node.encodeGoal()
    if seen.hasKeyOrPut(key, true):
      continue
    queue.add(node)
    if targetDepth == 0:
      result.atTarget.add(node)
    result.deepest.add(node)
  result.reached = 0

  var
    head = 0
    dequeued = 0
  while head < queue.len and dequeued < nodeCap:
    let node = queue[head]
    inc head
    inc dequeued
    if node.depth > result.reached:
      result.reached = node.depth
      result.deepest.setLen(0)
    if node.depth == result.reached:
      result.deepest.add(node)
    if node.depth >= targetDepth:
      continue
    work.boxes = node.boxes
    work.player = node.player
    work.blockedInto(blocked)
    blocked.floodFrom(node.player, region)
    for bi in 0 ..< BoxCount:
      let box = node.boxes[bi]
      for i in 0 .. 3:
        let back = Neighbours[box][i]
        if back < 0:
          continue
        let back2 = Neighbours[back][i]
        if back2 < 0 or blocked[back] or blocked[back2]:
          continue
        if not region[back2]:
          continue
        # The pull moves the box off `box` onto `back`; the flood that
        # normalises the successor's player runs over that mutated occupancy
        # and the two cells are restored straight after.
        blocked[box] = false
        blocked[back] = true
        blocked.floodFrom(back2, nextRegion)
        var normalised = back2
        for cell in 0 ..< GridCells:
          if nextRegion[cell]:
            normalised = cell
            break
        blocked[box] = true
        blocked[back] = false
        var next: GoalNode
        next.depth = node.depth + 1
        next.boxes = node.boxes
        next.boxes[bi] = back
        var sorter = LevelState(boxes: next.boxes)
        sorter.sortBoxes()
        next.boxes = sorter.boxes
        next.player = normalised
        let key = next.encodeGoal()
        if seen.hasKeyOrPut(key, true):
          continue
        queue.add(next)
        if next.depth == targetDepth:
          result.atTarget.add(next)
  if result.reached > targetDepth:
    result.reached = targetDepth

proc fallbackPath*(tier: Tier): string =
  FallbackLevelDir / ("fallback_" & $tier & ".xsb")

proc loadFallback*(tier: Tier): Level =
  ## The tier's committed hand-authored level. Three small files that ship in
  ## the repo and are also the fixtures the unit tests use. Reached only by a
  ## degenerate room, which the 5 000-seed sweep has never observed.
  let path = fallbackPath(tier)
  if not fileExists(path):
    raise newException(SokobanError,
      "fallback level missing: " & path)
  var rows: seq[string] = @[]
  var optPushes = 0
  for line in readFile(path).splitLines():
    if line.startsWith(";"):
      let parts = line.split('=')
      if parts.len == 2 and parts[0].strip() == "; optPushes":
        optPushes = parts[1].strip().parseInt()
      continue
    if line.len == 0:
      continue
    rows.add(line)
  result.state = parseXsb(rows)
  result.tier = tier
  result.optPushes = optPushes
  result.dead = result.state.board.deadSquares()
  result.tierRelaxed = true

proc generateLevel*(
  seed: int64, levelIndex: int, tier: Tier,
  genNodeCap = 200_000, genAttemptCap = 8
): Level =
  ## `generateLevel(seed, levelIndex, tier)` — the numbered procedure of the
  ## design note's §Level sourcing, exactly.
  var
    bestReached = -1
    bestDistance = high(int)
    bestAttempt = 0
    bestBoard: Board
    bestNode: GoalNode
    haveBest = false
  for attempt in 0 ..< max(1, genAttemptCap):
    var board = drawRoom(seed, levelIndex, attempt)
    if not board.floorConnected():
      continue
    if board.floorCells().len < 44:
      continue
    if not board.drawTargets(seed, levelIndex, attempt):
      continue
    var targets: seq[int] = @[]
    for cell in 0 ..< GridCells:
      if board.target[cell]:
        targets.add(cell)
    let
      bandMin = TierBandMin[tier]
      bandMax = TierBandMax[tier]
      targetDepth = bandMin + int(hashAt(seed, levelIndex, attempt, 300) mod
        uint64(bandMax - bandMin + 1))
      bfs = backwardBfs(board, targets, targetDepth, genNodeCap)

    proc pick(states: seq[GoalNode]): tuple[ok: bool, node: GoalNode] =
      if states.len == 0:
        return (false, GoalNode())
      let index = int(hashAt(seed, levelIndex, attempt, 400) mod
        uint64(states.len))
      # A level that starts a quarter solved is not a puzzle: reject a state
      # with more than one box already on a target, scanning forward in BFS
      # discovery order from the drawn index.
      for probe in 0 ..< states.len:
        let candidate = states[(index + probe) mod states.len]
        var parked = 0
        for box in candidate.boxes:
          if board.target[box]:
            inc parked
        if parked <= 1:
          return (true, candidate)
      (false, GoalNode())

    let chosen = pick(bfs.atTarget)
    if chosen.ok:
      var state = board.stateOf(chosen.node)
      # The player start is drawn from the chosen state's own region, in
      # ascending cell index.
      var region: seq[int] = @[]
      let flood = state.reachable()
      for cell in 0 ..< GridCells:
        if flood[cell]:
          region.add(cell)
      if region.len > 0:
        state.player = region[int(hashAt(seed, levelIndex, attempt, 500) mod
          uint64(region.len))]
      result.state = state
      result.tier = tier
      result.optPushes = targetDepth
      result.dead = board.deadSquares()
      result.tierRelaxed = false
      return
    ## Step 11: when no attempt hits the band, the level that ships is the
    ## attempt whose `reachedDepth` is CLOSEST TO bandMin — not the deepest
    ## one. Every attempt is clamped at its own `targetDepth` inside the band,
    ## so "deepest" and "closest to bandMin" pick different attempts whenever
    ## two straddle bandMin, and the relaxed level should be the one that
    ## misses the declared band by the least.
    let distance = abs(bfs.reached - bandMin)
    if distance < bestDistance:
      let relaxed = pick(bfs.deepest)
      if relaxed.ok:
        bestDistance = distance
        bestReached = bfs.reached
        bestAttempt = attempt
        bestBoard = board
        bestNode = relaxed.node
        haveBest = true

  if haveBest and bestReached >= 4:
    var state = bestBoard.stateOf(bestNode)
    var region: seq[int] = @[]
    let flood = state.reachable()
    for cell in 0 ..< GridCells:
      if flood[cell]:
        region.add(cell)
    if region.len > 0:
      ## The player cell is drawn from the hash stream of the attempt that
      ## produced this state, not from attempt 0's: every other draw for this
      ## level — the walls, the marked squares, the band depth, the state pick
      ## — is `mix64(seed, levelIndex, attempt, salt)` for THIS attempt, and
      ## reading a different attempt's word here made the player start the one
      ## quantity that did not come from the room it stands in. Still a pure
      ## function of `(seed, levelIndex, tier)`, so levels stay reproducible.
      state.player = region[int(hashAt(seed, levelIndex, bestAttempt, 500) mod
        uint64(region.len))]
    result.state = state
    result.tier = tier
    result.optPushes = bestReached
    result.dead = bestBoard.deadSquares()
    result.tierRelaxed = true
    return

  # No attempt produced a state at depth >= 4 — a degenerate room, never
  # observed over the 5 000-seed sweep. Take the tier's committed fallback.
  result = loadFallback(tier)
